# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-16.15
compiler: ghc-8.11
allow-newer: true
system-ghc: true

packages:
- '.'

# If you update the extra-deps, make sure to also update cabal.project
extra-deps:
- git: https://github.com/tweag/linear-base.git
  commit: 0d4713216b63aa8d1abb17b71c0ec0006c4dfbe5

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
